### ISSUE TITLE
Game Focus

### ISSUE THREAD

**Issue by MrDadpool-tech** [Lemo220/Lost_ark_chaos_dungeon_bot#14]
Is there a reason why you are using the current method of minimize and maximize when you could use:

Lost_ark = gw.getWindowsWithTitle('LOST ARK (64-bit, DX11)')[0]
        Lost_ark.activate()

This will ensure that the game itself is grabbed (regardless of version number) and won't confuse any other windows open which may have "lost ark" in the label [the only potential issue would be if they upgrade to DX12 in the future].

If there is a better reason I would really appreciate your input so that I can learn! :)

**Comment by MrDadpool-tech** [comment]
I noticed your latest update includes the game version number, you can remove that to avoid needing to update those parts of the script every time the game gets a new version applied.

**Comment by Lemo220** [comment]
Hey, I'm just learning python and deciding if I can focus window without importing any extra library maybe it's a good habit, and wanted to try how to do it with win32 to learn something :) Earlier I had a version with pygetwindow but one of my friends has a problem with this library work so maybe this will be more universal. Now not always grab the window if I don't put the exact window name with the version - later I'll do it to find the window name automatically.

**Comment by MrDadpool-tech** [comment]
Sounds good! I'm looking forward to what you learn. I've taken inspiration from you and created a bot to play songs for the charisma boosts,
