### ISSUE TITLE
no moudle named sreen-search，How to solve it？

### ISSUE THREAD

**Issue by killmemothedied** [Lemo220/Lost_ark_chaos_dungeon_bot#2]
no moudle named sreen-search，How to solve it

**Comment by Lemo220** [comment]
Hey, it was a useless library that I use in the test phase, I deleted it already.

**Comment by killmemothedied** [comment]
![QQ截图20220331000732](https://user-images.githubusercontent.com/35331534/160881871-3f7d5275-5cde-4d18-be66-7e7f68c781dd.png)
![QQ截图20220331000745](https://user-images.githubusercontent.com/35331534/160881887-78ffab11-8520-4080-baf9-2f7ea637663f.png)

Hey，Guys, this is a perfect project, but he's missing the last step, he's stuck at this point, and it would be perfect if we could solve it and re-match it

**Comment by Lemo220** [comment]
Forgot at it in readme. You have to put "Song of Escape" on slot "8" or configure it in code. It will use song to get back :) Sometimes it stuck but trying to repair it.

**Comment by Lemo220** [comment]
@killmemothedied Added new version, now it should work correctly, check it out.
