### ISSUE TITLE
The only thing the bot does is click G

### ISSUE THREAD

**Issue by sakminis** [Lemo220/Lost_ark_chaos_dungeon_bot#3]
As the title says, the bot doesn't do anything but open the window for the dungeon.

**Comment by Kokie6** [comment]
u need 1920 *1080 bordless effects medium

**Comment by sakminis** [comment]
> u need 1920 *1080 bordless effects medium

Thank you, i will try that. I have a 2k monitor which is why it could be f ing up, and also had settings higher im pretty sure.

**Comment by Lemo220** [comment]
Hey, as Kokie6 said, try to set 1920x1080 resolution. Also, the window with the game has to be at position 1x1. I'll try add it in the next update to position it automatically.

**Comment by Kokie6** [comment]
@Lemo220 we need auto repair and maybe just maybe smaller resolution in window mode :)

**Comment by sakminis** [comment]
> Hey, as Kokie6 said, try to set 1920x1080 resolution. Also, the window with the game has to be at position 1x1. I'll try add it in the next update to position it automatically.

What does position 1x1 mean or do? Im kinda clueless

**Comment by sakminis** [comment]
> u need 1920 *1080 bordless effects medium

There is a huge problem, i can't put that resolution in borderless for my monitor, it only does 2560 x 1440 borderless

**Comment by Kokie6** [comment]
same here so how i fix it is change the monitor resolution itself to 1920*1080 for it to work for me 
u can try that as temp fix till lemo220 can help/fix

**Comment by sakminis** [comment]
> same here so how i fix it is change the monitor resolution itself to 1920*1080 for it to work for me
u can try that as temp fix till lemo220 can help/fix

Okay thats too much just for a bot, im gonna wait then

**Comment by Lemo220** [comment]
I'll try to include rescale it but not sure if I can do it that fast. You can try to open config file (steam - > steam apps - >lost ark - > config / or something like that) and change resolution in this file (open with notepad), maybe it will force it to change.

**Comment by Lemo220** [comment]
@sakminis @Kokie6 Added new version, check it and let me know if it solve problems :)
