### ISSUE TITLE
Bot does not follow other players

### ISSUE THREAD

**Issue by ohitsjudd** [Lemo220/Lost_ark_chaos_dungeon_bot#4]
Bot moves around, joins games etc but the following does not appear to be working.

I would also suggest somehow making it so it will go to the mini boss and boss monsters when available

**Comment by Lemo220** [comment]
Hey, try to set transparency (right up corner) to 100%. This following system is very poor for now, i know it but on Sunday +/- one day I'll add new system :)

**Comment by Lemo220** [comment]
@ohitsjudd Added new version, now it should work much better, check it out
