### ISSUE TITLE
Spells 

### ISSUE THREAD

**Issue by Duili** [Lemo220/Lost_ark_chaos_dungeon_bot#5]
Hi i have a problem when i try to run the bot 

"ModuleNotFoundError: No module named 'spells' you know how to solve this ?

**Comment by Lemo220** [comment]
Hey, make sure spells.py is in same folder with main.py. Try to reset console also, on Sunday I'll add new update which will repair few bugs and increase efficiency, maybe it will help you :)

**Comment by Lemo220** [comment]
@Duili Added new version, now it should work much better, check it out
