### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by Kokie6** [Lemo220/Lost_ark_chaos_dungeon_bot#7]
new version it doesn't move for me inside dungeon it use skills but doesn't move

**Comment by Lemo220** [comment]
That's weird, testes od 3 computers and doesn't have problem with that. Try run it as administrator maybe, set transparency at 100% and zoom at 135%. Let me know if it helps you, if not, we will think more :)

**Comment by Lemo220** [comment]
Okay, I'll ask just to be sure, did you download the Images folder and replaced it with the old one?

**Comment by Kokie6** [comment]
yea

**Comment by Lemo220** [comment]
Maybe a stupid question but do you use "scale" on your windows? My friend has a problem with that, after setting it to 100, everything works great. You can also download the new version, maybe it will help also.  If not, let me know.

**Comment by Kokie6** [comment]
i will download it and try

**Comment by Lemo220** [comment]
Does it show any errors? And it uses spells or only auto attacking? 
I'll send you a .exe file, if you want, with packed everything, maybe that will help. Without any information, it's hard for me to find where is the problem :( 
https://easyupload.io/yiwzj1

**Comment by Lemo220** [comment]
@Kokie6 Try the new version, maybe it will help, changed the way how to capture screen and detect objects.

**Comment by Kokie6** [comment]
it detect the skills fine even matching and entering dungeon after it go inside the dungeon it use Z then some skills then auto attack idk why and just mouse doesn't move in the dungeon for direction or anything and at the end i leave the dungeon fine bot 
The old version mouse work fine it detect players and mouse move to there direction but not in the new version that's my problem.

**Comment by Lemo220** [comment]
It looks like there can be some problems with the threading module. Maybe try updating python version to the newest. Does the console give you any errors?

**Comment by Kokie6** [comment]
no it doesn't give me any errors

**Comment by Kokie6** [comment]
old version work fine

**Comment by Kokie6** [comment]
sure we can try the exe if it work then i will remove everything and reinstall

**Comment by Kokie6** [comment]
I finally got it working installed new windows and fresh installation for python working now ty <3

**Comment by Lemo220** [comment]
Glad to hear that :) Enjoy!
