### ISSUE TITLE
skills not being used with latest update

### ISSUE THREAD

**Issue by ohitsjudd** [Lemo220/Lost_ark_chaos_dungeon_bot#8]
Ran config.py and have config.txt but does not use any of the skills, previous version was with the skills.py

**Comment by killmemothedied** [comment]
Yeah, I had this problem too, I changed   config.txt to  config.py, but the character only moves but doesn't use skills

**Comment by Lemo220** [comment]
@ohitsjudd @killmemothedied 
Show me please how your config.txt looks like and go into images/ and show me your spells (q.png, a.png etc.)

**Comment by Lemo220** [comment]
I deleted spell.py and moved it into main. Config.txt is created after running config.py to set everything, main.py read from config what spells use and for how long. Download the new version and try it now, maybe it will help. Configure the bot from the beginning.

**Comment by ohitsjudd** [comment]
**config.txt:**
`spells = qwerasdfz
spell/time(s): f1
song of escape: 8`

![explorer_wUceEAd8as](https://user-images.githubusercontent.com/6566697/161638281-f644a9c8-1b27-4087-9ec3-e0665fc84f79.png)

**Comment by Lemo220** [comment]
@ohitsjudd you must stay in an area where you can use spells, not in the city (they are red if I'm not wrong)

**Comment by ohitsjudd** [comment]
Fixed images, worked once then not the 2nd time for some reason.
![explorer_HxQfRLeHnM](https://user-images.githubusercontent.com/6566697/161641888-e0127e7a-8834-4682-9921-3ae714da3ba9.png)

Also not sure how it would handle Shadow Hunter once in demon form as the icons then change
![LOSTARK_CFpDNokgY5](https://user-images.githubusercontent.com/6566697/161641983-9be39bac-aaa6-4668-b9c7-b6de94f182c8.png)

**Comment by Lemo220** [comment]
Did it show any errors/messages? Bot stop attacking/spells when he is too far from someone to get closer. For now, it won't work with new skills after a transformation so unfortunately, it's impossible to use it.

**Comment by killmemothedied** [comment]
@ohitsjudd OK Guys，I have solved all the problems, but I want to remove the normal attack, because it affects me to move with my teammates, which line should I delete it, or can I add an option in config config called whether to configure the normal attack?

**Comment by Lemo220** [comment]
Glad everything works now. The new update solves it or do you have to do something more? Delete 141-143 lines if you want to remove auto-attacking or decrease the range in 141 line "for _ in range(0,10):" to attack fewer times :)
